### PR TITLE
Translate strings to english

### PR DESCRIPTION
**Pull request by bedis-elacheche**

### CODE REVIEW

**Comment by giorgiofellipe** [comment]
Thanks @bedis-elacheche! I really appreciate your work. 

What do you think abou being able to choose the language? I mean, in some of my projects everything in portuguese is a requirement, as can be for other languages, so we could do something that will please everyone.

**Comment by bedis-elacheche** [comment]
Hi @giorgiofellipe. 
I think this is the best way for doing that. Actually, I was about to make it that way, but I had a busy day in the office and I needed those English strings instantly. Anyway, I'll try to add some strings.xml files to the project. asap. 
Thank you for your fast reply :+1:

**Comment by giorgiofellipe** [comment]
Oh, I see. Let me know if you need help.

Thanks in advance.

**Comment by giorgiofellipe** [comment]
Needed to work a bit on this cuz resources are treated in weird way in cordova plugins, but it's working fine now on 0.4.5

thanks @bedis-elacheche

**Pull request merged**
